language: ruby
cache: bundler
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7

gemfile:
  - gemfiles/Gemfile-rails.5.0.x
  - gemfiles/Gemfile-rails.5.1.x
  - gemfiles/Gemfile-rails.5.2.x
  - gemfiles/Gemfile-rails.head
  - Gemfile

matrix:
  exclude:
    - rvm: 2.4
      gemfile: Gemfile
    - rvm: 2.4
      gemfile: gemfiles/Gemfile-rails.head

notifications:
  email: true
